basePath: /api/v1
info:
  contact: {}
  description: This is a control server for managing Llama Server instances.
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
  title: Llama Server Control
  version: "1.0"
paths:
  /server/devices:
    get:
      description: Returns a list of available devices for the llama server
      responses:
        "200":
          description: List of devices
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List available devices for llama server
      tags:
      - server
  /server/help:
    get:
      description: Returns the help text for the llama server command
      responses:
        "200":
          description: Help text
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get help for llama server
      tags:
      - server
  /server/version:
    get:
      description: Returns the version of the llama server command
      responses:
        "200":
          description: Version information
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get version of llama server
      tags:
      - server
swagger: "2.0"
